{
 "title": "Caddy",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Response Time in Milliseconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (code) (rate(caddy_http_request_duration_seconds_count[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(caddy_http_request_errors_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Total Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(caddy_admin_http_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}