format_version: 10
pipelines:
  ci-server:
    group: Tools
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-36887ae:
        git: https://github.com/Poorna32/tools-automation-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    secure_variables:
      TF_VAR_vault_token: AES:OaIhuO1JgKgmKqlaBDqC1g==:FD3fAzlakILYiUSfLBtimpaDQ1p0IM74HXlOZ8MJB5o=
    stages:
      - Ansible:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            ansible:
              tasks:
                - exec: { command: ansible-playbook, arguments: [ "-i", "ci-server-internal.poornachandra3.online,", "tools.yml", "-e", "tool_name=ci-server", "-e", "ansible_user=ec2-user", "-e", "ansible_password=DevOps321" ],run_if: passed}
